### ISSUE TITLE
Unexpected Behaviour in the gradle run task

### ISSUE THREAD

**Issue by mirko-lelansky** [zyxist/chainsaw#4] opened 2017-11-01 11:11 UTC
Hallo,

i have found a strange behaviour in the gradle run task see [Working Example ](https://github.com/mirko-lelansky/java9-gradle-example-props).  That example reads a property file from the module|classpath and prints the property to the console. 

When you use the run task then the example didn't working because the Stream is null, but if you use the install task and then run the generate script the example works. 

I think the problem is that gradle separates the class and resource files in two separate directories. The module-info.class file which identify the module are only in the folder of the classes. Then when you use the run task both folders are add to the module path, but i think that the resouces aren't correctly recognized, because they have no module-info.class file.

**Comment by SingingBush** [comment] 2017-11-03 14:56
this is a problem for me. I have a unit test that uses a test resource but when running `gradle check` the resource is null

**Comment by zyxist** [comment] 2018-03-04 16:18
Sorry for the very late answer. Due to external circumstances I could not take care of the project for a while.

I managed to resolve the issue, although the root cause has something to do with Gradle internals, not with Jigsaw. The thing that helped was configuring `JavaExec` task with `doLast` closure, instead of `doFirst`. I added some integration tests both for `run` and `test` tasks.

**Comment by zyxist** [comment] 2018-03-08 06:00
Unfortunately, it turned out that the delivered fix disables Jigsaw completely for the `run` task. The tests did not capture it, because they did not look at the generated command line.

I managed to find a proper fix, will be merged later today.

**Closed** 2018-03-08 18:06 UTC
Labels: bug
